; ESP32 DEVKIT V1 (ESP-WROOM-32), ESP-IDF
; Платформа та же, что в TEST_ESP32_Relay (ESP-IDF 5.3).

[platformio]
src_dir = main

[env:esp32doit-devkit-v1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32doit-devkit-v1
framework = espidf
board_build.flash_mode = qio
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
