; ESP32-ETH01 → AW-PH350E (RS-422 / UART1), CLI + HTTP
; Библиотека: ../libs/ccam

[platformio]
default_envs = esp32_eth01
build_dir = ../.pio_core_root/build/ESP_CAM

[env:esp32_eth01]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32dev
framework = espidf
board_build.flash_mode = dio
board_upload.flash_size = 4MB
upload_speed = 115200
upload_flags =
    --before=no_reset
    --after=no_reset
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
    -std=gnu++17
build_unflags =
    -std=gnu++11
