#pragma once
// Generated by hmi2config.py from DMX.HMI
// Re-sync: python ../../syncHMI/hmi2config.py --update

#include "syncHMI/nexHmiSync.hpp"

namespace nex {
namespace hmi {

// GENERATED-HMI-BEGIN:summary
inline constexpr const char* kHmiSource = "NX4827P043_011";
inline constexpr const char* kHmiModel = "Nextion 4.3\" Intelligent 480x270";
inline constexpr uint16_t kScreenW = 480u;
inline constexpr uint16_t kScreenH = 272u;
inline constexpr uint8_t kPageCount = 1u;
inline constexpr bool kHaskeybdAPage = false;
inline constexpr bool kHaskeybdBPage = false;
inline constexpr bool kHaskeybdCPage = false;
// GENERATED-HMI-END:summary

// GENERATED-HMI-BEGIN:pages
#define HMI_PAGE_mon(X, ...) \
    X(mon, 0, ##__VA_ARGS__)

/** Page "mon" (panel page id 0). */
struct Page_mon {
    static constexpr uint8_t kPageId = 0u;

    enum Id : uint8_t {
        HMI_PAGE_mon(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_mon(HMI_NAME_ITEM)
    };
};
// GENERATED-HMI-END:pages

// GENERATED-HMI-BEGIN:fonts
// DMX.HMI
inline constexpr Font kFonts[] = {
    {2u, 20u, "20koi8-r"}, // ZI v6, width variable
};
// GENERATED-HMI-END:fonts

} // namespace hmi
} // namespace nex
