; Библиотека: lib/ccam  |  Пример: lib/ccam/examples/ptz_panel

[platformio]
default_envs = ptz_panel

[env:ptz_panel]
platform = ststm32
board = black_f407vg
framework = stm32cube
src_dir = lib/ccam/examples/ptz_panel/src
build_flags = -std=gnu++17
