#pragma once
// Generated by hmi2config.py from PUMS 2.5.HMI
// Re-sync: python ../../libs/Nextion/syncHMI/hmi2config.py --update -i "src/PUMS 2.5.HMI" -o "src/UI/nexHmiConfig.hpp"

#include "syncHMI/nexHmiSync.hpp"

namespace nex {
namespace hmi {

// GENERATED-HMI-BEGIN:summary
inline constexpr const char* kHmiSource = "NX1060P101_011";
inline constexpr const char* kHmiModel = "Nextion 10.0\" Intelligent 1024x600";
inline constexpr uint8_t kPageCount = 6u;
inline constexpr uint8_t kKeybdAPageId = 6u;
inline constexpr uint8_t kKeybdBPageId = 7u;
inline constexpr bool kHaskeybdAPage = true;
inline constexpr bool kHaskeybdBPage = true;
inline constexpr bool kHaskeybdCPage = false;
// GENERATED-HMI-END:summary

// GENERATED-HMI-BEGIN:pages
#define HMI_PAGE_wait(X, ...) \
    X(wait, 0, ##__VA_ARGS__)

/** Page "wait" (panel page id 0). */
struct Page_wait {
    static constexpr uint8_t kPageId = 0u;

    enum Id : uint8_t {
        HMI_PAGE_wait(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_wait(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_work(X, ...) \
    X(work, 0, ##__VA_ARGS__) \
    X(bSNext, 1, ##__VA_ARGS__) \
    X(bSPrev, 2, ##__VA_ARGS__) \
    X(t2, 3, ##__VA_ARGS__) \
    X(tgPage, 4, ##__VA_ARGS__) \
    X(t3, 5, ##__VA_ARGS__) \
    X(bS0, 6, ##__VA_ARGS__) \
    X(bS1, 7, ##__VA_ARGS__) \
    X(bS2, 8, ##__VA_ARGS__) \
    X(bS3, 9, ##__VA_ARGS__) \
    X(bS4, 10, ##__VA_ARGS__) \
    X(bS5, 11, ##__VA_ARGS__) \
    X(bS6, 12, ##__VA_ARGS__) \
    X(bS7, 13, ##__VA_ARGS__) \
    X(bFile, 14, ##__VA_ARGS__) \
    X(t0, 15, ##__VA_ARGS__) \
    X(bBlock, 16, ##__VA_ARGS__) \
    X(bShow, 17, ##__VA_ARGS__) \
    X(t1, 18, ##__VA_ARGS__) \
    X(bSa0, 19, ##__VA_ARGS__) \
    X(bSa1, 20, ##__VA_ARGS__) \
    X(bSa2, 21, ##__VA_ARGS__) \
    X(bSa3, 22, ##__VA_ARGS__) \
    X(bSa4, 23, ##__VA_ARGS__) \
    X(bSa5, 24, ##__VA_ARGS__) \
    X(bSa6, 25, ##__VA_ARGS__) \
    X(bSa7, 26, ##__VA_ARGS__) \
    X(b0, 27, ##__VA_ARGS__) \
    X(b1, 28, ##__VA_ARGS__) \
    X(b2, 29, ##__VA_ARGS__) \
    X(b3, 30, ##__VA_ARGS__) \
    X(b4, 31, ##__VA_ARGS__) \
    X(b5, 32, ##__VA_ARGS__) \
    X(b6, 33, ##__VA_ARGS__) \
    X(b7, 34, ##__VA_ARGS__) \
    X(b8, 35, ##__VA_ARGS__) \
    X(b9, 36, ##__VA_ARGS__) \
    X(b10, 37, ##__VA_ARGS__) \
    X(b11, 38, ##__VA_ARGS__) \
    X(b12, 39, ##__VA_ARGS__) \
    X(b13, 40, ##__VA_ARGS__) \
    X(b14, 41, ##__VA_ARGS__) \
    X(b15, 42, ##__VA_ARGS__) \
    X(b16, 43, ##__VA_ARGS__) \
    X(b17, 44, ##__VA_ARGS__) \
    X(b18, 45, ##__VA_ARGS__) \
    X(b19, 46, ##__VA_ARGS__) \
    X(b20, 47, ##__VA_ARGS__) \
    X(b21, 48, ##__VA_ARGS__) \
    X(b22, 49, ##__VA_ARGS__) \
    X(b23, 50, ##__VA_ARGS__) \
    X(b24, 51, ##__VA_ARGS__) \
    X(t6, 52, ##__VA_ARGS__) \
    X(tc, 53, ##__VA_ARGS__) \
    X(gName, 54, ##__VA_ARGS__)

/** Page "work" (panel page id 1). */
struct Page_work {
    static constexpr uint8_t kPageId = 1u;

    enum Id : uint8_t {
        HMI_PAGE_work(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_work(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_mGroup(X, ...) \
    X(mGroup, 0, ##__VA_ARGS__) \
    X(t0, 1, ##__VA_ARGS__) \
    X(tPan, 2, ##__VA_ARGS__) \
    X(bClr, 3, ##__VA_ARGS__) \
    X(bRen, 4, ##__VA_ARGS__) \
    X(bRec, 5, ##__VA_ARGS__) \
    X(bSa, 6, ##__VA_ARGS__)

/** Page "mGroup" (panel page id 2). */
struct Page_mGroup {
    static constexpr uint8_t kPageId = 2u;

    enum Id : uint8_t {
        HMI_PAGE_mGroup(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_mGroup(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_mFile(X, ...) \
    X(mFile, 0, ##__VA_ARGS__) \
    X(t0, 1, ##__VA_ARGS__) \
    X(tPan, 2, ##__VA_ARGS__) \
    X(bSave, 3, ##__VA_ARGS__) \
    X(bOpen, 4, ##__VA_ARGS__) \
    X(bNew, 5, ##__VA_ARGS__) \
    X(bFile, 6, ##__VA_ARGS__) \
    X(bSaveAs, 7, ##__VA_ARGS__) \
    X(bDel, 8, ##__VA_ARGS__) \
    X(bSettings, 9, ##__VA_ARGS__)

/** Page "mFile" (panel page id 3). */
struct Page_mFile {
    static constexpr uint8_t kPageId = 3u;

    enum Id : uint8_t {
        HMI_PAGE_mFile(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_mFile(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_browser(X, ...) \
    X(browser, 0, ##__VA_ARGS__) \
    X(bF7, 1, ##__VA_ARGS__) \
    X(fName, 2, ##__VA_ARGS__) \
    X(title, 3, ##__VA_ARGS__) \
    X(mBack, 4, ##__VA_ARGS__) \
    X(t0, 5, ##__VA_ARGS__) \
    X(t6, 6, ##__VA_ARGS__) \
    X(bAction, 7, ##__VA_ARGS__) \
    X(bFNext, 8, ##__VA_ARGS__) \
    X(bFPrev, 9, ##__VA_ARGS__) \
    X(tfPage, 10, ##__VA_ARGS__) \
    X(t2, 11, ##__VA_ARGS__) \
    X(t1, 12, ##__VA_ARGS__) \
    X(t7, 13, ##__VA_ARGS__) \
    X(bF0, 14, ##__VA_ARGS__) \
    X(bF1, 15, ##__VA_ARGS__) \
    X(bF2, 16, ##__VA_ARGS__) \
    X(bF3, 17, ##__VA_ARGS__) \
    X(bF4, 18, ##__VA_ARGS__) \
    X(bF5, 19, ##__VA_ARGS__) \
    X(bF6, 20, ##__VA_ARGS__) \
    X(bCancel, 21, ##__VA_ARGS__) \
    X(bF0d, 22, ##__VA_ARGS__) \
    X(bF1d, 23, ##__VA_ARGS__) \
    X(bF2d, 24, ##__VA_ARGS__) \
    X(bF3d, 25, ##__VA_ARGS__) \
    X(bF4d, 26, ##__VA_ARGS__) \
    X(bF5d, 27, ##__VA_ARGS__) \
    X(bF6d, 28, ##__VA_ARGS__) \
    X(bF7d, 29, ##__VA_ARGS__) \
    X(tfNum, 30, ##__VA_ARGS__) \
    X(tm, 31, ##__VA_ARGS__) \
    X(mode, 32, ##__VA_ARGS__) \
    X(fNameStr, 33, ##__VA_ARGS__)

/** Page "browser" (panel page id 4). */
struct Page_browser {
    static constexpr uint8_t kPageId = 4u;

    enum Id : uint8_t {
        HMI_PAGE_browser(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_browser(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_settings(X, ...) \
    X(settings, 0, ##__VA_ARGS__) \
    X(title, 1, ##__VA_ARGS__) \
    X(mBack, 2, ##__VA_ARGS__) \
    X(t0, 3, ##__VA_ARGS__) \
    X(t6, 4, ##__VA_ARGS__) \
    X(bAction, 5, ##__VA_ARGS__) \
    X(bCancel, 6, ##__VA_ARGS__) \
    X(swGr0, 7, ##__VA_ARGS__) \
    X(t1, 8, ##__VA_ARGS__) \
    X(nThour, 9, ##__VA_ARGS__) \
    X(nTmin, 10, ##__VA_ARGS__) \
    X(t2, 11, ##__VA_ARGS__) \
    X(t3, 12, ##__VA_ARGS__) \
    X(t4, 13, ##__VA_ARGS__) \
    X(nTsec, 14, ##__VA_ARGS__) \
    X(nDday, 15, ##__VA_ARGS__) \
    X(nDmon, 16, ##__VA_ARGS__) \
    X(t5, 17, ##__VA_ARGS__) \
    X(t7, 18, ##__VA_ARGS__) \
    X(nDyear, 19, ##__VA_ARGS__) \
    X(t8, 20, ##__VA_ARGS__) \
    X(t9, 21, ##__VA_ARGS__) \
    X(t10, 22, ##__VA_ARGS__) \
    X(t11, 23, ##__VA_ARGS__)

/** Page "settings" (panel page id 5). */
struct Page_settings {
    static constexpr uint8_t kPageId = 5u;

    enum Id : uint8_t {
        HMI_PAGE_settings(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_settings(HMI_NAME_ITEM)
    };
};
// GENERATED-HMI-END:pages

} // namespace hmi
} // namespace nex
