#pragma once
// Generated by hmi2config.py from PUMS 2.3.HMI
// Re-sync: python ../../syncHMI/hmi2config.py --update

#include "syncHMI/nexHmiSync.hpp"

namespace nex {
namespace hmi {

// GENERATED-HMI-BEGIN:summary
inline constexpr const char* kHmiSource = "NX1060P101_011";
inline constexpr const char* kHmiModel = "Nextion 10.0\" Intelligent 1024x600";
inline constexpr uint8_t kPageCount = 5u;
inline constexpr uint8_t kKeybdAPageId = 5u;
inline constexpr bool kHaskeybdAPage = true;
inline constexpr bool kHaskeybdBPage = false;
inline constexpr bool kHaskeybdCPage = false;
// GENERATED-HMI-END:summary

// GENERATED-HMI-BEGIN:pages
#define HMI_PAGE_wait(X, ...) \
    X(wait, 0, ##__VA_ARGS__)

/** Page "wait" (panel page id 0). */
struct Page_wait {
    static constexpr uint8_t kPageId = 0u;

    enum class Id : uint8_t {
        HMI_PAGE_wait(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_wait(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_work(X, ...) \
    X(work, 0, ##__VA_ARGS__) \
    X(bSNext, 1, ##__VA_ARGS__) \
    X(bSPrev, 2, ##__VA_ARGS__) \
    X(t2, 3, ##__VA_ARGS__) \
    X(tgPage, 4, ##__VA_ARGS__) \
    X(t3, 5, ##__VA_ARGS__) \
    X(bS0, 6, ##__VA_ARGS__) \
    X(bS1, 7, ##__VA_ARGS__) \
    X(bS2, 8, ##__VA_ARGS__) \
    X(bS3, 9, ##__VA_ARGS__) \
    X(bS4, 10, ##__VA_ARGS__) \
    X(bS5, 11, ##__VA_ARGS__) \
    X(bS6, 12, ##__VA_ARGS__) \
    X(bS7, 13, ##__VA_ARGS__) \
    X(bFile, 14, ##__VA_ARGS__) \
    X(t0, 15, ##__VA_ARGS__) \
    X(tSt, 16, ##__VA_ARGS__) \
    X(tTime, 17, ##__VA_ARGS__) \
    X(bBlock, 18, ##__VA_ARGS__) \
    X(bShow, 19, ##__VA_ARGS__) \
    X(t1, 20, ##__VA_ARGS__) \
    X(bSa0, 21, ##__VA_ARGS__) \
    X(bSa1, 22, ##__VA_ARGS__) \
    X(bSa2, 23, ##__VA_ARGS__) \
    X(bSa3, 24, ##__VA_ARGS__) \
    X(bSa4, 25, ##__VA_ARGS__) \
    X(bSa5, 26, ##__VA_ARGS__) \
    X(bSa6, 27, ##__VA_ARGS__) \
    X(bSa7, 28, ##__VA_ARGS__) \
    X(b0, 29, ##__VA_ARGS__) \
    X(b1, 30, ##__VA_ARGS__) \
    X(b2, 31, ##__VA_ARGS__) \
    X(b3, 32, ##__VA_ARGS__) \
    X(b4, 33, ##__VA_ARGS__) \
    X(b5, 34, ##__VA_ARGS__) \
    X(b6, 35, ##__VA_ARGS__) \
    X(b7, 36, ##__VA_ARGS__) \
    X(b8, 37, ##__VA_ARGS__) \
    X(b9, 38, ##__VA_ARGS__) \
    X(b10, 39, ##__VA_ARGS__) \
    X(b11, 40, ##__VA_ARGS__) \
    X(b12, 41, ##__VA_ARGS__) \
    X(b13, 42, ##__VA_ARGS__) \
    X(b14, 43, ##__VA_ARGS__) \
    X(b15, 44, ##__VA_ARGS__) \
    X(b16, 45, ##__VA_ARGS__) \
    X(b17, 46, ##__VA_ARGS__) \
    X(b18, 47, ##__VA_ARGS__) \
    X(b19, 48, ##__VA_ARGS__) \
    X(b20, 49, ##__VA_ARGS__) \
    X(b21, 50, ##__VA_ARGS__) \
    X(b22, 51, ##__VA_ARGS__) \
    X(b23, 52, ##__VA_ARGS__) \
    X(b24, 53, ##__VA_ARGS__) \
    X(tFile, 54, ##__VA_ARGS__) \
    X(t6, 55, ##__VA_ARGS__) \
    X(tc, 56, ##__VA_ARGS__) \
    X(gName, 57, ##__VA_ARGS__)

/** Page "work" (panel page id 1). */
struct Page_work {
    static constexpr uint8_t kPageId = 1u;

    enum class Id : uint8_t {
        HMI_PAGE_work(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_work(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_mGroup(X, ...) \
    X(mGroup, 0, ##__VA_ARGS__) \
    X(t0, 1, ##__VA_ARGS__) \
    X(tPan, 2, ##__VA_ARGS__) \
    X(bClr, 3, ##__VA_ARGS__) \
    X(bRen, 4, ##__VA_ARGS__) \
    X(bRec, 5, ##__VA_ARGS__) \
    X(bSa, 6, ##__VA_ARGS__) \
    X(tTime, 7, ##__VA_ARGS__) \
    X(gbid, 8, ##__VA_ARGS__)

/** Page "mGroup" (panel page id 2). */
struct Page_mGroup {
    static constexpr uint8_t kPageId = 2u;

    enum class Id : uint8_t {
        HMI_PAGE_mGroup(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_mGroup(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_mFile(X, ...) \
    X(mFile, 0, ##__VA_ARGS__) \
    X(t0, 1, ##__VA_ARGS__) \
    X(tPan, 2, ##__VA_ARGS__) \
    X(bSave, 3, ##__VA_ARGS__) \
    X(bOpen, 4, ##__VA_ARGS__) \
    X(bNew, 5, ##__VA_ARGS__) \
    X(tTime, 6, ##__VA_ARGS__) \
    X(bFile, 7, ##__VA_ARGS__) \
    X(bSaveAs, 8, ##__VA_ARGS__) \
    X(bDel, 9, ##__VA_ARGS__)

/** Page "mFile" (panel page id 3). */
struct Page_mFile {
    static constexpr uint8_t kPageId = 3u;

    enum class Id : uint8_t {
        HMI_PAGE_mFile(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_mFile(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_browser(X, ...) \
    X(browser, 0, ##__VA_ARGS__) \
    X(title, 1, ##__VA_ARGS__) \
    X(mBack, 2, ##__VA_ARGS__) \
    X(t0, 3, ##__VA_ARGS__) \
    X(tSt, 4, ##__VA_ARGS__) \
    X(tFile, 5, ##__VA_ARGS__) \
    X(t6, 6, ##__VA_ARGS__) \
    X(tTime, 7, ##__VA_ARGS__) \
    X(bAction, 8, ##__VA_ARGS__) \
    X(bFNext, 9, ##__VA_ARGS__) \
    X(bFPrev, 10, ##__VA_ARGS__) \
    X(t4, 11, ##__VA_ARGS__) \
    X(t2, 12, ##__VA_ARGS__) \
    X(t1, 13, ##__VA_ARGS__) \
    X(t7, 14, ##__VA_ARGS__) \
    X(bF0, 15, ##__VA_ARGS__) \
    X(bF1, 16, ##__VA_ARGS__) \
    X(bF2, 17, ##__VA_ARGS__) \
    X(bF3, 18, ##__VA_ARGS__) \
    X(bF4, 19, ##__VA_ARGS__) \
    X(bF5, 20, ##__VA_ARGS__) \
    X(bF6, 21, ##__VA_ARGS__) \
    X(bF7, 22, ##__VA_ARGS__) \
    X(tc, 23, ##__VA_ARGS__) \
    X(b0, 24, ##__VA_ARGS__) \
    X(bF0d, 25, ##__VA_ARGS__) \
    X(bF1d, 26, ##__VA_ARGS__) \
    X(bF2d, 27, ##__VA_ARGS__) \
    X(bF3d, 28, ##__VA_ARGS__) \
    X(bF4d, 29, ##__VA_ARGS__) \
    X(bF5d, 30, ##__VA_ARGS__) \
    X(bF6d, 31, ##__VA_ARGS__) \
    X(bF7d, 32, ##__VA_ARGS__) \
    X(t15, 33, ##__VA_ARGS__) \
    X(tm, 34, ##__VA_ARGS__) \
    X(mode, 35, ##__VA_ARGS__) \
    X(fNameStr, 36, ##__VA_ARGS__) \
    X(fName, 37, ##__VA_ARGS__)

/** Page "browser" (panel page id 4). */
struct Page_browser {
    static constexpr uint8_t kPageId = 4u;

    enum class Id : uint8_t {
        HMI_PAGE_browser(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_browser(HMI_NAME_ITEM)
    };
};
// GENERATED-HMI-END:pages

} // namespace hmi
} // namespace nex
