#pragma once
// Generated by hmi2config.py from Server 1.HMI
// Re-sync: python ../../libs/Nextion/syncHMI/hmi2config.py --update -i "src/Server 1.HMI" -o "src/ServerUI/nexHmiConfig.hpp"

#include "syncHMI/nexHmiSync.hpp"

namespace nex {
namespace hmi {

// GENERATED-HMI-BEGIN:summary
inline constexpr const char* kHmiSource = "NX4827P043_011";
inline constexpr const char* kHmiModel = "Nextion 4.3\" Intelligent 480x270";
inline constexpr uint8_t kPageCount = 1u;
inline constexpr bool kHaskeybdAPage = false;
inline constexpr bool kHaskeybdBPage = false;
inline constexpr bool kHaskeybdCPage = false;
// GENERATED-HMI-END:summary

// GENERATED-HMI-BEGIN:pages
#define HMI_PAGE_page0(X, ...) \
    X(page0, 0, ##__VA_ARGS__) \
    X(cnsl, 1, ##__VA_ARGS__)

/** Page "page0" (panel page id 0). */
struct Page_page0 {
    static constexpr uint8_t kPageId = 0u;

    enum Id : uint8_t {
        HMI_PAGE_page0(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_page0(HMI_NAME_ITEM)
    };
};
// GENERATED-HMI-END:pages

} // namespace hmi
} // namespace nex
