#pragma once
// Generated by hmi2config.py from ПУМС 2.2.HMI
// Re-sync: python ../../syncHMI/hmi2config.py --update

#include "syncHMI/nexHmiSync.hpp"

namespace nex {
namespace hmi {

// GENERATED-HMI-BEGIN:summary
inline constexpr const char* kHmiSource = "NX1060P101_011";
inline constexpr const char* kHmiModel = "Nextion 10.0\" Intelligent 1024x600";
inline constexpr uint8_t kPageCount = 7u;
// GENERATED-HMI-END:summary

// GENERATED-HMI-BEGIN:pages
#define HMI_PAGE_pgWait(X) \
    X(pgWait, 0) \
    X(t0, 1) \
    X(tPress, 2) \
    X(tmLabel, 3) \
    X(tSt, 4)

/** Page "pgWait" (panel page id 0). */
struct Page_pgWait {
    static constexpr uint8_t kPageId = 0u;

    enum class Id : uint8_t {
        HMI_PAGE_pgWait(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_pgWait(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_pgFiles(X) \
    X(pgFiles, 0) \
    X(fSelect, 1) \
    X(bCmd, 2) \
    X(bCancel, 3) \
    X(FileName, 4) \
    X(tTitle, 5) \
    X(tSt, 6)

/** Page "pgFiles" (panel page id 1). */
struct Page_pgFiles {
    static constexpr uint8_t kPageId = 1u;

    enum class Id : uint8_t {
        HMI_PAGE_pgFiles(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_pgFiles(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_mScn(X) \
    X(mScn, 0) \
    X(t0, 1) \
    X(t2, 2) \
    X(t1, 3) \
    X(bsmClear, 4) \
    X(bsmRecord, 5) \
    X(bsmRename, 6) \
    X(bsmScene, 7) \
    X(tmClear, 8) \
    X(tmRecord, 9) \
    X(tmRename, 10) \
    X(q0, 11) \
    X(bS0, 12) \
    X(bS1, 13) \
    X(bS5, 14) \
    X(bS4, 15) \
    X(bS6, 16) \
    X(bS7, 17) \
    X(bS3, 18) \
    X(bS2, 19) \
    X(tSt, 20)

/** Page "mScn" (panel page id 2). */
struct Page_mScn {
    static constexpr uint8_t kPageId = 2u;

    enum class Id : uint8_t {
        HMI_PAGE_mScn(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_mScn(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_mFile(X) \
    X(mFile, 0) \
    X(t0, 1) \
    X(t2, 2) \
    X(t1, 3) \
    X(b1, 4) \
    X(b0, 5) \
    X(b2, 6) \
    X(b3, 7) \
    X(b4, 8) \
    X(bFile, 9)

/** Page "mFile" (panel page id 3). */
struct Page_mFile {
    static constexpr uint8_t kPageId = 3u;

    enum class Id : uint8_t {
        HMI_PAGE_mFile(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_mFile(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_MsgBox(X) \
    X(MsgBox, 0) \
    X(t0, 1) \
    X(t1, 2) \
    X(bCancel, 3) \
    X(bYes, 4) \
    X(tMsg, 5) \
    X(bOK, 6) \
    X(bNo, 7)

/** Page "MsgBox" (panel page id 4). */
struct Page_MsgBox {
    static constexpr uint8_t kPageId = 4u;

    enum class Id : uint8_t {
        HMI_PAGE_MsgBox(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_MsgBox(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_pgWork(X) \
    X(pgWork, 0) \
    X(tc, 1) \
    X(b0, 2) \
    X(b1, 3) \
    X(b2, 4) \
    X(b3, 5) \
    X(b4, 6) \
    X(b5, 7) \
    X(b6, 8) \
    X(b7, 9) \
    X(b8, 10) \
    X(b9, 11) \
    X(b10, 12) \
    X(b11, 13) \
    X(b12, 14) \
    X(b13, 15) \
    X(b14, 16) \
    X(b15, 17) \
    X(b16, 18) \
    X(b17, 19) \
    X(b18, 20) \
    X(b19, 21) \
    X(b20, 22) \
    X(b21, 23) \
    X(b22, 24) \
    X(b23, 25) \
    X(ctrlClear, 26) \
    X(ctrlSelAll, 27) \
    X(bS0, 28) \
    X(bS1, 29) \
    X(bS2, 30) \
    X(bS3, 31) \
    X(bS4, 32) \
    X(bS5, 33) \
    X(bS6, 34) \
    X(bS7, 35) \
    X(bSNext, 36) \
    X(bSPrev, 37) \
    X(mFile, 38) \
    X(t0, 39) \
    X(tSt, 40) \
    X(tPg, 41) \
    X(bsmScene, 42) \
    X(tmrBlock, 43) \
    X(sBlock, 44) \
    X(varScnName, 45) \
    X(t1, 46) \
    X(sShow, 47)

/** Page "pgWork" (panel page id 5). */
struct Page_pgWork {
    static constexpr uint8_t kPageId = 5u;

    enum class Id : uint8_t {
        HMI_PAGE_pgWork(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_pgWork(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_keybdA(X) \
    X(keybdA, 0) \
    X(t0, 1) \
    X(loadpageid, 2) \
    X(loadcmpid, 3) \
    X(b0, 4) \
    X(b251, 5) \
    X(b1, 6) \
    X(b2, 7) \
    X(b3, 8) \
    X(b4, 9) \
    X(b5, 10) \
    X(b6, 11) \
    X(b7, 12) \
    X(b8, 13) \
    X(b200, 14) \
    X(b20, 15) \
    X(b21, 16) \
    X(b22, 17) \
    X(b23, 18) \
    X(b24, 19) \
    X(b25, 20) \
    X(b26, 21) \
    X(b27, 22) \
    X(b28, 23) \
    X(b220, 24) \
    X(b40, 25) \
    X(b41, 26) \
    X(b42, 27) \
    X(b43, 28) \
    X(b44, 29) \
    X(b45, 30) \
    X(b46, 31) \
    X(b47, 32) \
    X(b240, 33) \
    X(b48, 34) \
    X(refshow, 35) \
    X(tm0, 36) \
    X(input, 37) \
    X(show, 38) \
    X(temp, 39) \
    X(inputlenth, 40) \
    X(b9, 41) \
    X(temp2, 42) \
    X(tempstr, 43) \
    X(b10, 44) \
    X(b11, 45) \
    X(b29, 46) \
    X(b30, 47) \
    X(b242, 48) \
    X(b210, 49)

/** Page "keybdA" (panel page id 6). */
struct Page_keybdA {
    static constexpr uint8_t kPageId = 6u;

    enum class Id : uint8_t {
        HMI_PAGE_keybdA(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_keybdA(HMI_NAME_ITEM)
    };
};
// GENERATED-HMI-END:pages

} // namespace hmi
} // namespace nex
