#pragma once
// Generated by hmi2config.py from ПУМС 2.2.HMI
// Re-sync: python ../../syncHMI/hmi2config.py --update

#include "syncHMI/nexHmiSync.hpp"

namespace nex {
namespace hmi {

// GENERATED-HMI-BEGIN:summary
inline constexpr const char* kHmiSource = "NX1060P101_011";
inline constexpr const char* kHmiModel = "Nextion 10.0\" Intelligent 1024x600";
inline constexpr uint8_t kPageCount = 7u;
// GENERATED-HMI-END:summary

// GENERATED-HMI-BEGIN:pages
#define HMI_PAGE_pgWait(X, ...) \
    X(pgWait, 0, ##__VA_ARGS__) \
    X(t0, 1, ##__VA_ARGS__) \
    X(tPress, 2, ##__VA_ARGS__) \
    X(tmLabel, 3, ##__VA_ARGS__) \
    X(tSt, 4, ##__VA_ARGS__)

/** Page "pgWait" (panel page id 0). */
struct Page_pgWait {
    static constexpr uint8_t kPageId = 0u;

    enum class Id : uint8_t {
        HMI_PAGE_pgWait(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_pgWait(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_pgFiles(X, ...) \
    X(pgFiles, 0, ##__VA_ARGS__) \
    X(fSelect, 1, ##__VA_ARGS__) \
    X(bCmd, 2, ##__VA_ARGS__) \
    X(bCancel, 3, ##__VA_ARGS__) \
    X(FileName, 4, ##__VA_ARGS__) \
    X(tTitle, 5, ##__VA_ARGS__) \
    X(tSt, 6, ##__VA_ARGS__)

/** Page "pgFiles" (panel page id 1). */
struct Page_pgFiles {
    static constexpr uint8_t kPageId = 1u;

    enum class Id : uint8_t {
        HMI_PAGE_pgFiles(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_pgFiles(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_mScn(X, ...) \
    X(mScn, 0, ##__VA_ARGS__) \
    X(t0, 1, ##__VA_ARGS__) \
    X(t2, 2, ##__VA_ARGS__) \
    X(t1, 3, ##__VA_ARGS__) \
    X(bsmClear, 4, ##__VA_ARGS__) \
    X(bsmRecord, 5, ##__VA_ARGS__) \
    X(bsmRename, 6, ##__VA_ARGS__) \
    X(bsmScene, 7, ##__VA_ARGS__) \
    X(tmClear, 8, ##__VA_ARGS__) \
    X(tmRecord, 9, ##__VA_ARGS__) \
    X(tmRename, 10, ##__VA_ARGS__) \
    X(q0, 11, ##__VA_ARGS__) \
    X(bS0, 12, ##__VA_ARGS__) \
    X(bS1, 13, ##__VA_ARGS__) \
    X(bS5, 14, ##__VA_ARGS__) \
    X(bS4, 15, ##__VA_ARGS__) \
    X(bS6, 16, ##__VA_ARGS__) \
    X(bS7, 17, ##__VA_ARGS__) \
    X(bS3, 18, ##__VA_ARGS__) \
    X(bS2, 19, ##__VA_ARGS__) \
    X(tSt, 20, ##__VA_ARGS__)

/** Page "mScn" (panel page id 2). */
struct Page_mScn {
    static constexpr uint8_t kPageId = 2u;

    enum class Id : uint8_t {
        HMI_PAGE_mScn(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_mScn(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_mFile(X, ...) \
    X(mFile, 0, ##__VA_ARGS__) \
    X(t0, 1, ##__VA_ARGS__) \
    X(t2, 2, ##__VA_ARGS__) \
    X(t1, 3, ##__VA_ARGS__) \
    X(b1, 4, ##__VA_ARGS__) \
    X(b0, 5, ##__VA_ARGS__) \
    X(b2, 6, ##__VA_ARGS__) \
    X(b3, 7, ##__VA_ARGS__) \
    X(b4, 8, ##__VA_ARGS__) \
    X(bFile, 9, ##__VA_ARGS__)

/** Page "mFile" (panel page id 3). */
struct Page_mFile {
    static constexpr uint8_t kPageId = 3u;

    enum class Id : uint8_t {
        HMI_PAGE_mFile(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_mFile(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_MsgBox(X, ...) \
    X(MsgBox, 0, ##__VA_ARGS__) \
    X(t0, 1, ##__VA_ARGS__) \
    X(t1, 2, ##__VA_ARGS__) \
    X(bCancel, 3, ##__VA_ARGS__) \
    X(bYes, 4, ##__VA_ARGS__) \
    X(tMsg, 5, ##__VA_ARGS__) \
    X(bOK, 6, ##__VA_ARGS__) \
    X(bNo, 7, ##__VA_ARGS__)

/** Page "MsgBox" (panel page id 4). */
struct Page_MsgBox {
    static constexpr uint8_t kPageId = 4u;

    enum class Id : uint8_t {
        HMI_PAGE_MsgBox(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_MsgBox(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_pgWork(X, ...) \
    X(pgWork, 0, ##__VA_ARGS__) \
    X(tc, 1, ##__VA_ARGS__) \
    X(b0, 2, ##__VA_ARGS__) \
    X(b1, 3, ##__VA_ARGS__) \
    X(b2, 4, ##__VA_ARGS__) \
    X(b3, 5, ##__VA_ARGS__) \
    X(b4, 6, ##__VA_ARGS__) \
    X(b5, 7, ##__VA_ARGS__) \
    X(b6, 8, ##__VA_ARGS__) \
    X(b7, 9, ##__VA_ARGS__) \
    X(b8, 10, ##__VA_ARGS__) \
    X(b9, 11, ##__VA_ARGS__) \
    X(b10, 12, ##__VA_ARGS__) \
    X(b11, 13, ##__VA_ARGS__) \
    X(b12, 14, ##__VA_ARGS__) \
    X(b13, 15, ##__VA_ARGS__) \
    X(b14, 16, ##__VA_ARGS__) \
    X(b15, 17, ##__VA_ARGS__) \
    X(b16, 18, ##__VA_ARGS__) \
    X(b17, 19, ##__VA_ARGS__) \
    X(b18, 20, ##__VA_ARGS__) \
    X(b19, 21, ##__VA_ARGS__) \
    X(b20, 22, ##__VA_ARGS__) \
    X(b21, 23, ##__VA_ARGS__) \
    X(b22, 24, ##__VA_ARGS__) \
    X(b23, 25, ##__VA_ARGS__) \
    X(ctrlClear, 26, ##__VA_ARGS__) \
    X(ctrlSelAll, 27, ##__VA_ARGS__) \
    X(bS0, 28, ##__VA_ARGS__) \
    X(bS1, 29, ##__VA_ARGS__) \
    X(bS2, 30, ##__VA_ARGS__) \
    X(bS3, 31, ##__VA_ARGS__) \
    X(bS4, 32, ##__VA_ARGS__) \
    X(bS5, 33, ##__VA_ARGS__) \
    X(bS6, 34, ##__VA_ARGS__) \
    X(bS7, 35, ##__VA_ARGS__) \
    X(bSNext, 36, ##__VA_ARGS__) \
    X(bSPrev, 37, ##__VA_ARGS__) \
    X(mFile, 38, ##__VA_ARGS__) \
    X(t0, 39, ##__VA_ARGS__) \
    X(tSt, 40, ##__VA_ARGS__) \
    X(tPg, 41, ##__VA_ARGS__) \
    X(bsmScene, 42, ##__VA_ARGS__) \
    X(tmrBlock, 43, ##__VA_ARGS__) \
    X(sBlock, 44, ##__VA_ARGS__) \
    X(varScnName, 45, ##__VA_ARGS__) \
    X(t1, 46, ##__VA_ARGS__) \
    X(sShow, 47, ##__VA_ARGS__)

/** Page "pgWork" (panel page id 5). */
struct Page_pgWork {
    static constexpr uint8_t kPageId = 5u;

    enum class Id : uint8_t {
        HMI_PAGE_pgWork(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_pgWork(HMI_NAME_ITEM)
    };
};

#define HMI_PAGE_keybdA(X, ...) \
    X(keybdA, 0, ##__VA_ARGS__) \
    X(t0, 1, ##__VA_ARGS__) \
    X(loadpageid, 2, ##__VA_ARGS__) \
    X(loadcmpid, 3, ##__VA_ARGS__) \
    X(b0, 4, ##__VA_ARGS__) \
    X(b251, 5, ##__VA_ARGS__) \
    X(b1, 6, ##__VA_ARGS__) \
    X(b2, 7, ##__VA_ARGS__) \
    X(b3, 8, ##__VA_ARGS__) \
    X(b4, 9, ##__VA_ARGS__) \
    X(b5, 10, ##__VA_ARGS__) \
    X(b6, 11, ##__VA_ARGS__) \
    X(b7, 12, ##__VA_ARGS__) \
    X(b8, 13, ##__VA_ARGS__) \
    X(b200, 14, ##__VA_ARGS__) \
    X(b20, 15, ##__VA_ARGS__) \
    X(b21, 16, ##__VA_ARGS__) \
    X(b22, 17, ##__VA_ARGS__) \
    X(b23, 18, ##__VA_ARGS__) \
    X(b24, 19, ##__VA_ARGS__) \
    X(b25, 20, ##__VA_ARGS__) \
    X(b26, 21, ##__VA_ARGS__) \
    X(b27, 22, ##__VA_ARGS__) \
    X(b28, 23, ##__VA_ARGS__) \
    X(b220, 24, ##__VA_ARGS__) \
    X(b40, 25, ##__VA_ARGS__) \
    X(b41, 26, ##__VA_ARGS__) \
    X(b42, 27, ##__VA_ARGS__) \
    X(b43, 28, ##__VA_ARGS__) \
    X(b44, 29, ##__VA_ARGS__) \
    X(b45, 30, ##__VA_ARGS__) \
    X(b46, 31, ##__VA_ARGS__) \
    X(b47, 32, ##__VA_ARGS__) \
    X(b240, 33, ##__VA_ARGS__) \
    X(b48, 34, ##__VA_ARGS__) \
    X(refshow, 35, ##__VA_ARGS__) \
    X(tm0, 36, ##__VA_ARGS__) \
    X(input, 37, ##__VA_ARGS__) \
    X(show, 38, ##__VA_ARGS__) \
    X(temp, 39, ##__VA_ARGS__) \
    X(inputlenth, 40, ##__VA_ARGS__) \
    X(b9, 41, ##__VA_ARGS__) \
    X(temp2, 42, ##__VA_ARGS__) \
    X(tempstr, 43, ##__VA_ARGS__) \
    X(b10, 44, ##__VA_ARGS__) \
    X(b11, 45, ##__VA_ARGS__) \
    X(b29, 46, ##__VA_ARGS__) \
    X(b30, 47, ##__VA_ARGS__) \
    X(b242, 48, ##__VA_ARGS__) \
    X(b210, 49, ##__VA_ARGS__)

/** Page "keybdA" (panel page id 6). */
struct Page_keybdA {
    static constexpr uint8_t kPageId = 6u;

    enum class Id : uint8_t {
        HMI_PAGE_keybdA(HMI_ENUM_ITEM)
    };

    static constexpr const char* kNames[] = {
        HMI_PAGE_keybdA(HMI_NAME_ITEM)
    };
};
// GENERATED-HMI-END:pages

} // namespace hmi
} // namespace nex
